Kennwortlänge in eine Variable überführt
BITS-Training/BITS-hugo pull request #94
Opened 2022-01-06 11:06 UTC by hagen-bauer-rc

Um BITS auf die organisationsspezifischen Anforderungen für die Kennwortlänge anpassen zu können, schlage ich vor eine Variable einzuführen, die an den verschiedenen Stellen aufgerufen wird.

2022-01-07 08:23 UTC, BITS-Editor commented
Ich finde beides gut. @andi-blafasl : Was meinst Du?

2022-01-07 08:25 UTC, BITS-Editor requested changes
Finde ich beides gut. Die innere Readme-Datei muss dann noch angepasst werden.

2022-01-11 15:39 UTC, andi-blafasl commented
@hagen-bauer-rc 
Die Variable für die Kennwortlänge ist gut. Das würden wir übernehmen. Auch die Anpassung mit dem "blind" nehmen wir.

Die Anpassung bei der privaten Nutzung der E-Mail gehört hier aber nicht in den Pull Request. Deine Lösung mit der eingebundenen Datei finde ich auch nicht schön und ich bin mir auch nicht sicher welche Auswirkungen das sonst noch hat.

Ich schau ob ich den Pull Request anpassen kann, wenn nicht, dann müssest Du ihn ändern.

2022-01-13 16:37 UTC, hagen-bauer-rc commented
Ok, ich habe wieder etwas über das Arbeiten mit Git gelernt. Mein Vorschlag ist ich machte zwei neue PR für die zwei verschiedenen Änderungen. Die Konfigurationsmöglichkeiten für die Inhalte der E-Mail Nutzung sind aufgrund eines Denkfehlers auf meiner Seite hier reingerutscht. Wäre das so OK?

2022-01-13 18:03 UTC, BITS-Editor commented
> Ok, ich habe wieder etwas über das Arbeiten mit Git gelernt. Mein Vorschlag ist ich machte zwei neue PR für die zwei verschiedenen Änderungen. Die Konfigurationsmöglichkeiten für die Inhalte der E-Mail Nutzung sind aufgrund eines Denkfehlers auf meiner Seite hier reingerutscht. Wäre das so OK?

Meines Erachtens könnte man einen PR für die Kennwort-Länge und "blind" machen und den anderen weglassen. Das würde ich begrüßen - und dann noch die innere Readme anpassen, um auf die neue Variable hinzuweisen. Das kann ich aber gerne übernehmen.

2022-01-14 11:29 UTC, hagen-bauer-rc commented
> Die Anpassung bei der privaten Nutzung der E-Mail gehört hier aber nicht in den Pull Request. Deine Lösung mit der eingebundenen Datei finde ich auch nicht schön und ich bin mir auch nicht sicher welche Auswirkungen das sonst noch hat.

Was gefällt Dir nicht an der Lösung? Ich wollte eine Art Plugin Mechanismus implementieren der eine regelmäßiges Update von dem Gitrepo erlaubt und lokale Erweiterungen "ignoriert". Ich habe noch weitere Bereich identifiziert in denen so etwas notwendig ist. Folgende Kapitel mit Texten als Beispiele (es gibt noch mehr) 
- 0602 Zwar werden Web-Zugriffe schon am Netzknoten Ihrer Einrichtung auf Viren und schädliche Programme untersucht. 
- 0605 In den meisten Behörden und Einrichtungen ist eine sichere Konfiguration des Browsers fest vorgegeben!
- 0607 Einige Behörden und Einrichtungen stellen mit Hilfe von zentralen Filtersystemen sicher, 
- 0901 Auch Behörden und andere Einrichtungen nutzen heute bereits Cloud-Dienste! 

Das sind Textpassagen, die auf jeden Fall für eine Org angepasst werden müssen. Damit die Updatefahigkeit erhalten bleibt und nicht jedes Mal umfangreiche diffs gefahren werden müssen braucht es eine Art Plugin.

2022-01-15 19:49 UTC, andi-blafasl commented
@hagen-bauer-rc Du hast für deine Anpassungen MarkDown Dateien innerhalb des "Content"-Ordners verwendet. Diese werden dann von Hugo auch als HTML-Dateien gerendert, tauchen im Menü Links und auch in der Sitemap auf. Das macht doch so keinen Sinn, oder?
Für Anpassungen wie du sie gern hättest, mach einfach ein eigenes Repository und nimm unser BITS als zusätlichen Remote mit auf. Dann kann du alles Anpassen was du willst und GIT ist so intelligent, das bei einem Merge von unserem BITS zu deiner Angepassten Kopie nur die Änderungen übernommen werden. Sollten wir in deinen angepassten Dateien ebenfalls Änderungen vornehmen, dann gibt es einen Konflikt und du musst ihn im Zuge des Merges lösen. Das ist einfacher als irgendwelche Diffs und auch ohne selbstgestrickte Plugins ziemlich easy machbar.
Genau aus diesem Grund, wegen der einfach Anpassung des Inhalts, haben  wir die Kombination aus GIT und Hugo gewählt. Arbeite dich entsprechend in GIT ein und Du wirst sehen das es ganz easy ist. Für deinen Fork musst du es ja schon in einer ähnlichen Art machen. Siehe dazu auch https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date

2022-01-16 09:07 UTC, hagen-bauer-rc commented
Guter Punkt mit der Navigation, das ist mir nicht aufgefallen. Das scheint man mit einem 
`ignoreFiles = [ 'anpassungen' ]
`
lösen zu können. 

Und natürlich hast Du recht das man das Problem auch durch Kenntnisse von git lösen kann. An meiner eigenen Lernkurve kann ich allerdings sagen das diese Lernkurve nicht gerade flach ist . Auch die ganzen Variablen sollen ja verhindern, dass man unbedingt mit Git arbeiten muss. Sonst könnte man ja auch sagen wir lassen die Variablen bleiben und sagen das alle Nutzer das mit Git lösen könnten.

2022-01-17 19:45 UTC, closed without merging