Kennwortlänge in einer zentralen Variable
BITS-Training/BITS-hugo pull request #98
Opened 2022-01-14 11:08 UTC by hagen-bauer-rc

2022-01-14 11:34 UTC, BITS-Editor requested changes
Bitte im der config.toml BITS_Password_Length = "acht" vorbelegen.

2022-01-16 09:11 UTC, hagen-bauer-rc commented
done

2022-01-17 13:46 UTC, BITS-Editor approved these changes

2022-01-17 19:17 UTC, andi-blafasl approved these changes
passt

2022-01-17 19:20 UTC, merged